apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  containers:
    - name: frontend
      image: rkalluru/frontend
#      ports: #(this is on pod level but it is not working)
#        - hostPort: 30678 #(kubectl has a port range from 30k to 34k )
#          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-roboshop
spec:
  type: NodePort #(this is on service level which will open random port)
  selector:
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  containers:
    - name: cart
      image: rkalluru/cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart-roboshop
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: catalogue
#  labels:
#    component: catalogue
#spec:
#  containers:
#    - name: catalogue
#      image: rkalluru/catalogue
#      env:
#        - name: DOCUMENTDB
#          value: "true"
#        - name: MONGO_URL
#          value: "mongodb://admin1:RoboShop123@prod-docdb-cluster.cluster-ccs4h9brfzmd.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: catalogue
  #replica set labels
  labels:
    component: catalogue
spec:
  replicas: 4
  selector:
    # selector labels for pods, meaning pods are attached to to replicaset liks service svc in replicaset using these selectors
    matchLabels:
      component: catalogue
  template:
    metadata:
      # pod labels
      labels:
        component: catalogue
    spec:
      containers:
        - name: catalogue
          image: rkalluru/cart
          env:
            - name: DOCUMENTDB
              value: "true"
            - name: MONGO_URL
              value: "mongodb://admin1:RoboShop123@prod-docdb-cluster.cluster-ccs4h9brfzmd.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-roboshop
spec:
  selector:
    component: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    component: user
spec:
  containers:
    - name: user
      image: rkalluru/user

---
apiVersion: v1
kind: Service
metadata:
  name: user-roboshop
spec:
  selector:
    component: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    component: shipping
spec:
  containers:
    - name: shipping
      image: rkalluru/shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-roboshop
spec:
  selector:
    component: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    component: payment
spec:
  containers:
    - name: payment
      image: rkalluru/payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment-roboshop
spec:
  selector:
    component: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---