apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}-roboshop
spec:
  selector:
    name: {{ .Values.component }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}