FROM            dokken/centos-8
ENV             URL=google.com
#COPY            mongodb.repo /etc/yum.repos.d/mongodb.repo
ADD             https://raw.githubusercontent.com/raghudevopsb70/roboshop-ansible/main/roles/mongodb/files/mongodb.repo