apiVersion: v1
kind: Pod
metadata:
  name: 3-service
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: service-3
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80