apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
    - image: centos:8
      name: centos
      command: [ "sleep", "10000" ]
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir:
        sizeLimit: 500Mi